import { Law } from "../types";

export const evidenceLaws: Law[] = [
  {
    id: 1301,
    category: "evidence",
    title: "Bharatiya Sakshya Adhiniyam (BSA) 2023",
    subtitle: "Replaced Indian Evidence Act 1872 — Effective July 1, 2024",
    sections: [
      { no: "Section 2(1)(c)", title: "Definition of Document", keywords: ["document", "definition", "electronic", "written", "map", "plan", "data"], summary: "'Document' means any matter expressed or described upon any substance by means of letters, figures, or marks, or by more than one of those means, intended to be used, or which may be used, for the purpose of recording that matter, and includes electronic or digital record, server logs, computer generated documents, emails, messages and websites." },
      { no: "Section 2(1)(e)", title: "Definition of Evidence", keywords: ["evidence", "definition", "oral", "documentary", "electronic", "proof"], summary: "'Evidence' means and includes: all statements which the Court permits or requires to be made before it by witnesses, in relation to matters of fact under inquiry — such statements are called oral evidence; all documents including electronic records produced for the inspection of the Court — such documents are called documentary evidence." },
      { no: "Section 3", title: "Admissibility of Electronic Records", keywords: ["electronic record", "admissible", "evidence", "Section 65B", "certificate", "digital"], summary: "Notwithstanding anything contained in this Act, any information contained in an electronic record which is printed on a paper, stored, recorded or copied in optical or magnetic media produced by a computer shall be deemed to be also a document if the conditions mentioned in this section are satisfied in relation to the information and computer in question and shall be admissible in any proceedings, without further proof or production of the original, as evidence of any contents of the original or any fact stated therein of which direct evidence would be admissible." },
      { no: "Section 9", title: "Facts Which Need Not Be Proved — Judicial Notice", keywords: ["judicial notice", "facts", "proof", "common knowledge", "court", "official"], summary: "No fact of which the Court will take judicial notice need be proved. The Court shall take judicial notice of: all laws in force in India; the course of proceedings of Parliament and the Legislatures of the States; the accession and the sign manual of every person who has at any time been, and of the person who is for the time being, the Sovereign of the United Kingdom of Great Britain and Ireland; the seals of all the Courts in India; the seals of all Courts out of India; the existence, title and national flag of every State or Sovereign recognised by the Government of India." },
      { no: "Section 16", title: "Relevancy of Facts Forming Part of Same Transaction — Res Gestae", keywords: ["res gestae", "same transaction", "relevant", "spontaneous", "contemporaneous", "part of"], summary: "Facts which, though not in issue, are so connected with a fact in issue as to form part of the same transaction, are relevant, whether they occurred at the same time and place or at different times and places. This is the principle of res gestae — statements made contemporaneously with the act are admissible." },
      { no: "Section 22", title: "Relevancy of Admission — Against Interest", keywords: ["admission", "party", "statement", "against interest", "relevant", "own words"], summary: "An admission is a statement, oral or documentary or contained in electronic form, which suggests any inference as to any fact in issue or relevant fact, and which is made by any of the persons, and under the circumstances, hereinafter mentioned. An admission made by a party is relevant as a statement against his own interest." },
      { no: "Section 25", title: "Confession to Police Officer — Not Provable", keywords: ["confession", "police", "not provable", "custodial", "coercion", "voluntary"], summary: "No confession made to a police officer shall be proved as against a person accused of any offence. A confession made by a person while they are in the custody of a police officer also cannot be proved against them unless made in the immediate presence of a Magistrate." },
      { no: "Section 26", title: "Confession by Accused While in Custody of Police Not to Be Proved Against Him", keywords: ["confession", "custody", "police", "magistrate", "prove against", "accused"], summary: "No confession made by any person whilst he is in the custody of a police officer, unless it be made in the immediate presence of a Magistrate, shall be proved as against such person. A confession must be voluntary, true and should not have been obtained by inducement, threat or promise." },
      { no: "Section 30", title: "How Much of Information Received from Accused May Be Proved", keywords: ["discovery", "information", "accused", "police", "admissible", "facts discovered"], summary: "When any fact is deposed to as discovered in consequence of information received from a person accused of any offence, in the custody of a police officer, so much of such information, whether it amounts to a confession or not, as relates distinctly to the fact thereby discovered, may be proved." },
      { no: "Section 57", title: "Proof of Signature and Handwriting", keywords: ["signature", "handwriting", "prove", "witness", "expert", "comparison"], summary: "In order to ascertain whether a signature, writing or seal is that of the person by whom it purports to have been written or made, any signature, writing or seal admitted or proved to the satisfaction of the Court to have been written or made by that person may be submitted for comparison with the one which is to be proved although that signature, writing or seal has not been produced or proved for any other purpose." },
      { no: "Section 63", title: "Primary Evidence — Best Evidence Rule", keywords: ["primary evidence", "original document", "best evidence", "court", "production"], summary: "Primary evidence means the document itself produced for the inspection of the Court. If the original document is available, it must be produced. Secondary evidence is admitted only in specific situations such as when the original has been destroyed, lost, or is in the possession of the opponent who refuses to produce it." },
      { no: "Section 65A", title: "Special Provisions as to Evidence Relating to Electronic Records", keywords: ["electronic evidence", "admissible", "condition", "certificate", "65B", "digital record"], summary: "The contents of electronic records may be proved in accordance with the provisions of section 65B." },
      { no: "Section 74", title: "Burden of Proof", keywords: ["burden of proof", "who must prove", "plaintiff", "prosecution", "fact in issue"], summary: "Whoever desires any Court to give judgment as to any legal right or liability dependent on the existence of facts which he asserts, must prove that those facts exist. When a person is bound to prove the existence of any fact, it is said that the burden of proof lies on that person." },
      { no: "Section 75", title: "On Whom Burden of Proof Lies — General Rule", keywords: ["burden of proof", "general rule", "prosecution", "accused", "civil", "criminal"], summary: "The burden of proof in a suit or proceeding lies on that person who would fail if no evidence at all were given on either side. In criminal cases, the prosecution bears the burden of proving the guilt of the accused beyond reasonable doubt. In civil cases, the party asserting a fact must prove it on a balance of probabilities." },
      { no: "Section 111", title: "Refreshing Memory of Witnesses", keywords: ["memory", "refresh", "witness", "document", "past recollection", "record"], summary: "A witness may, while under examination, refresh his memory by referring to any writing made by himself at the time of the transaction concerning which he is questioned, or so soon afterwards that the Court considers it likely that the transaction was at that time fresh in his memory." },
      { no: "Section 119", title: "Witness Who is Unable to Communicate Verbally", keywords: ["dumb witness", "sign language", "communicate", "court", "evidence", "disability"], summary: "A witness who is unable to speak may give his evidence in any other manner in which he can make it intelligible, as by writing or by signs; but such writing must be written and the signs made in open court. Evidence so given shall be deemed to be oral evidence." },
    ],
  },
];
