import { Law } from "../types";

export const ipLaws: Law[] = [
  {
    id: 1101,
    category: "ip",
    title: "Patents Act 1970",
    subtitle: "Grants patents for inventions in India",
    sections: [
      { no: "Section 2(1)(j)", title: "Definition of Invention", keywords: ["invention", "definition", "new", "novel", "non-obvious", "patent"], summary: "'Invention' means a new product or process involving an inventive step and capable of industrial application. An inventive step means a feature of an invention that involves technical advance as compared to the existing knowledge or having economic significance or both and that makes the invention not obvious to a person skilled in the art." },
      { no: "Section 2(1)(l)", title: "Definition of Patent", keywords: ["patent", "definition", "exclusive right", "20 years", "invention"], summary: "'Patent' means a patent for any invention granted under this Act. A patent grants the holder the exclusive right to make, use, offer for sale, sell, or import the patented invention in India for a period of 20 years from the date of filing." },
      { no: "Section 3", title: "Inventions Not Patentable", keywords: ["not patentable", "discovery", "scientific principle", "traditional knowledge", "mathematics", "business method"], summary: "The following are not inventions for the purposes of this Act: an invention which is frivolous or which claims anything obviously contrary to well established natural laws; a discovery of a scientific principle or formulation of an abstract theory or discovery of any living thing or non-living substance occurring in nature; a mathematical or business method or a computer programme per se or algorithms; a method of agriculture or horticulture; any process for the medicinal, surgical, curative, prophylactic diagnostic, therapeutic or other treatment of human beings." },
      { no: "Section 3(d)", title: "Section 3(d) — New Forms of Known Substance Not Patentable", keywords: ["3d", "new form", "known substance", "efficacy", "evergreening", "pharmaceutical"], summary: "The mere discovery of a new form of a known substance which does not result in the enhancement of the known efficacy of that substance is not patentable. This provision is specifically directed at preventing 'evergreening' of pharmaceutical patents — i.e., pharmaceutical companies cannot extend patent protection by making minor changes to existing drugs without demonstrating improved efficacy. This section was central to the Novartis v. Union of India (2013) Supreme Court case." },
      { no: "Section 5", title: "Inventions Where Only Methods or Processes of Manufacture are Patentable — Pre-2005 Rule", keywords: ["pharmaceutical", "food", "chemical", "product patent", "2005 amendment"], summary: "With effect from 1st January 2005, the Patents Act was amended to allow product patents for all fields including pharmaceuticals, food and chemicals, in compliance with India's WTO-TRIPS obligations. Prior to 2005, only process patents were allowed for food, chemicals and pharmaceutical substances." },
      { no: "Section 25", title: "Opposition to Grant of Patent", keywords: ["opposition", "patent", "pre-grant", "post-grant", "third party", "challenge"], summary: "Where an application for a patent has been published but a patent has not been granted, any person may give notice of opposition to the Controller in the prescribed manner. Grounds for pre-grant opposition include: anticipation; obviousness; non-patentable subject matter; sufficiency of description; failure to disclose source of biological material." },
      { no: "Section 47", title: "Grant of Patents to be Subject to Certain Conditions — Government Use", keywords: ["government use", "compulsory license", "public non-commercial use", "patent", "state"], summary: "Every patent granted under this Act shall be subject to the condition that any machine, apparatus or other article in respect of which the patent is granted or any article made by using a process in respect of which the patent is granted, may be imported or made by or on behalf of the Government for the purpose merely of its own use." },
      { no: "Section 84", title: "Compulsory Licence — Application After 3 Years", keywords: ["compulsory license", "affordable", "public health", "3 years", "reasonable requirements", "public interest"], summary: "At any time after the expiration of three years from the date of the grant of a patent, any person interested may make an application to the Controller for grant of compulsory licence on patent. Grounds: that the reasonable requirements of the public with respect to the patented invention have not been satisfied; the patented invention is not available to the public at a reasonably affordable price; or the patented invention is not worked in the territory of India." },
      { no: "Section 104", title: "Suit for Infringement Not to Be Instituted Except in High Court", keywords: ["infringement", "High Court", "suit", "patent", "exclusive jurisdiction"], summary: "No suit for the infringement of a patent shall be instituted in any court inferior to a District Court having jurisdiction to try the suit: and where a counter-claim for revocation of the patent is made by the defendant, the suit, along with the counter-claim, shall be transferred to the High Court for decision." },
    ],
  },
  {
    id: 1102,
    category: "ip",
    title: "Copyright Act 1957",
    subtitle: "Protects original works of authorship in India",
    sections: [
      { no: "Section 13", title: "Works in Which Copyright Subsists", keywords: ["copyright", "original works", "literary", "artistic", "musical", "dramatic", "cinematograph"], summary: "Subject to the provisions of this section and the other provisions of this Act, copyright shall subsist throughout India in original literary, dramatic, musical and artistic works; cinematograph films; sound recordings." },
      { no: "Section 14", title: "Meaning of Copyright", keywords: ["copyright", "exclusive right", "reproduce", "publish", "communicate", "adapt"], summary: "For the purposes of this Act, 'copyright' means the exclusive right subject to the provisions of this Act, to do or authorise the doing of any of the following acts in respect of a work or any substantial part thereof, namely: in the case of a literary, dramatic or musical work, to reproduce the work in any material form including the storing of it in any medium by electronic means; to issue copies of the work to the public; to perform the work in public; to communicate the work to the public." },
      { no: "Section 17", title: "First Owner of Copyright — Employer and Employee Works", keywords: ["first owner", "copyright", "employer", "employee", "work for hire", "author"], summary: "Subject to the provisions of this Act, the author of a work shall be the first owner of the copyright therein. Provided that in the case of a work made by an author in the course of his employment under a contract of service or apprenticeship, the employer shall, in the absence of any agreement to the contrary, be the first owner of the copyright in the work." },
      { no: "Section 22", title: "Term of Copyright — Life Plus 60 Years", keywords: ["copyright term", "life", "60 years", "duration", "literary", "artistic"], summary: "Copyright in a literary, dramatic, musical or artistic work (other than a photograph) shall subsist for sixty years from the beginning of the calendar year next following the year in which the author dies (i.e., life of author plus 60 years). For posthumous works, it's 60 years from publication." },
      { no: "Section 51", title: "When Copyright Is Infringed", keywords: ["infringement", "copyright", "unauthorised", "reproduction", "distribute", "communicate"], summary: "Copyright in a work shall be deemed to be infringed when any person, without a licence granted by the owner of the copyright or the Registrar of Copyrights, does anything the exclusive right to do which is by this Act conferred upon the owner of the copyright. Also infringed by permitting for profit any place for the performance of the work, or by importing infringing copies." },
      { no: "Section 52", title: "Certain Acts Not to be Infringement — Fair Use/Fair Dealing", keywords: ["fair use", "fair dealing", "research", "private study", "criticism", "news reporting", "exception"], summary: "The following acts shall not constitute an infringement of copyright: a fair dealing with any work for the purpose of private or personal use, including research; criticism or review, whether of that work or of any other work; reporting of current events and current affairs, including the reporting of a lecture delivered in public; the reproduction of any work for the purpose of judicial proceeding." },
      { no: "Section 63", title: "Offence of Infringement of Copyright — Criminal Liability", keywords: ["criminal", "copyright", "infringement", "imprisonment", "fine", "piracy"], summary: "Any person who knowingly infringes or abets the infringement of the copyright in a work, or any other right conferred by this Act, shall be punishable with imprisonment for a term which shall not be less than six months but which may extend to three years and with fine which shall not be less than fifty thousand rupees but which may extend to two lakh rupees." },
    ],
  },
  {
    id: 1103,
    category: "ip",
    title: "Trade Marks Act 1999",
    subtitle: "Protects marks used in trade in India",
    sections: [
      { no: "Section 2(1)(zb)", title: "Definition of Trade Mark", keywords: ["trademark", "definition", "mark", "distinctive", "goods", "services"], summary: "'Trade mark' means a mark capable of being represented graphically and which is capable of distinguishing the goods or services of one person from those of others and may include shape of goods, their packaging and combination of colours. A mark includes a device, brand, heading, label, ticket, name, signature, word, letter, numeral, shape of goods, packaging, combination of colours, sound mark." },
      { no: "Section 9", title: "Absolute Grounds for Refusal of Registration", keywords: ["absolute grounds", "refusal", "registration", "generic", "descriptive", "deceptive"], summary: "A trade mark shall not be registered if it is devoid of any distinctive character; if it consists exclusively of marks or indications which may serve in trade to designate the kind, quality, quantity, intended purpose, values, geographical origin or the time of production of the goods or rendering of the service; if it consists exclusively of marks or indications which have become customary in the current language or in the bona fide and established practices of the trade." },
      { no: "Section 11", title: "Relative Grounds for Refusal of Registration — Likelihood of Confusion", keywords: ["confusion", "likelihood", "similar mark", "refusal", "identical", "earlier trademark"], summary: "A trade mark shall not be registered if, because of its identity with an earlier trade mark and the identity or similarity of the goods or services covered by the trade mark, there exists a likelihood of confusion on the part of the public, which includes the likelihood of association with the earlier trade mark." },
      { no: "Section 29", title: "Infringement of Registered Trade Marks", keywords: ["infringement", "trademark", "identical", "similar", "confusion", "use in course of trade"], summary: "A registered trade mark is infringed by a person who, not being a registered proprietor or a person using by way of permitted use, uses in the course of trade, a mark which is identical with, or deceptively similar to, the trade mark in relation to goods or services in respect of which the trade mark is registered and in such manner as to render the use of the mark likely to be taken as being used as a trade mark." },
      { no: "Section 103", title: "Penalty for Applying False Trade Marks — Criminal Liability", keywords: ["false trademark", "criminal", "penalty", "imprisonment", "counterfeiting", "fraud"], summary: "Any person who applies any false trade mark or trade description to goods or services; sells, lets for hire, or exposes for sale, or hires or has in his possession, goods or things to which any false trade mark or false trade description is applied; makes, disposes of, or has in his possession, any die, block, machine, plate or other instrument for the purpose of applying any such mark to goods — shall be punishable with imprisonment for a term which shall not be less than six months but which may extend to three years and with fine which shall not be less than fifty thousand rupees but which may extend to two lakh rupees." },
    ],
  },
];
