import { Law } from "../types";

export const laborLaws: Law[] = [
  {
    id: 701,
    category: "labor",
    title: "Industrial Disputes Act 1947",
    subtitle: "Governs industrial disputes and labour rights",
    sections: [
      { no: "Section 2(k)", title: "Definition of Industrial Dispute", keywords: ["industrial dispute", "definition", "worker", "employer", "dispute", "labour"], summary: "'Industrial dispute' means any dispute or difference between employers and employers, or between employers and workmen, or between workmen and workmen, which is connected with the employment or non-employment or the terms of employment or with the conditions of labour, of any person." },
      { no: "Section 2(s)", title: "Definition of Workman", keywords: ["workman", "definition", "worker", "skilled", "manual", "clerical", "supervisory"], summary: "'Workman' means any person (including an apprentice) employed in any industry to do any manual, unskilled, skilled, technical, operational, clerical or supervisory work for hire or reward, whether the terms of employment be express or implied, and for the purposes of any proceeding under this Act in relation to an industrial dispute, includes any such person who has been dismissed, discharged or retrenched in connection with, or as a consequence of, that dispute." },
      { no: "Section 22", title: "Prohibition of Strikes and Lock-Outs — Notice Requirement", keywords: ["strike", "lockout", "notice", "six weeks", "14 days", "prohibition", "essential services"], summary: "No person employed in a public utility service shall go on strike in breach of contract without giving to the employer notice of strike within six weeks before striking, or within fourteen days of giving such notice. No employer carrying on any public utility service shall lock-out any of his workmen without giving them notice of lock-out as hereinafter provided, or within fourteen days of giving such notice." },
      { no: "Section 25B", title: "Definition of Continuous Service — One Year", keywords: ["continuous service", "190 days", "one year", "workman", "employment", "retrenchment"], summary: "For the purposes of this Chapter, a workman shall be said to be in continuous service for a period if he is, for that period, in uninterrupted service, including service which may be interrupted on account of sickness or authorised leave or an accident or a strike which is not illegal or a lock-out or a cessation of work which is not due to any fault on the part of the workman. A workman shall be deemed to be in continuous service for not less than one year if he has worked for 190 days in an establishment that does not work throughout the year or 240 days in others." },
      { no: "Section 25C", title: "Right of Workmen Laid Off for Compensation", keywords: ["layoff", "compensation", "50 percent", "workman", "wages", "right"], summary: "Whenever a workman (other than a badli workman or a casual workman) whose name is borne on the muster rolls of an industrial establishment and who has completed not less than one year of continuous service under an employer is laid off, he shall be paid by the employer for all days during which he is so laid off, except for such weekly holidays as may intervene, compensation which shall be equal to fifty per cent of the total of the basic wages and dearness allowance that would have been payable to him had he not been so laid off." },
      { no: "Section 25F", title: "Conditions Precedent to Retrenchment of Workmen", keywords: ["retrenchment", "layoff", "termination", "notice", "compensation", "15 days pay"], summary: "No workman employed in any industry who has been in continuous service for not less than one year under an employer shall be retrenched by that employer until the workman has been given one month's notice in writing indicating the reasons for retrenchment and the period of notice has expired, or the workman has been paid in lieu of such notice, wages for the period of the notice; and the workman has been paid, at the time of retrenchment, compensation which shall be equivalent to fifteen days' average pay for every completed year of continuous service or any part thereof in excess of six months." },
      { no: "Section 25G", title: "Procedure for Retrenchment — Last In First Out", keywords: ["LIFO", "last in first out", "retrenchment", "seniority", "procedure"], summary: "Where any workman in an industrial establishment, who is a citizen of India, is to be retrenched and he belongs to a particular category of workmen in that establishment, in the absence of any agreement between the employer and the workman in this behalf, the employer shall ordinarily retrench the workman who was the last person to be employed in that category, unless for reasons to be recorded the employer retrenches any other workman." },
      { no: "Section 25H", title: "Re-employment of Retrenched Workmen", keywords: ["re-employment", "retrenched", "right", "vacancy", "seniority", "preference"], summary: "Where any workmen are retrenched, and the employer proposes to take into his employ any persons, he shall, in such manner as may be prescribed, give an opportunity to the retrenched workmen who are citizens of India to offer themselves for re-employment, and such retrenched workmen who offer themselves for re-employment shall have preference over other persons." },
      { no: "Section 25N", title: "Conditions Precedent to Closure of Undertaking — 100 or More Workers", keywords: ["closure", "100 workers", "government permission", "establishment", "closure compensation"], summary: "No employer who employs one hundred or more workmen in an industrial establishment shall close down the establishment unless the employer has served at least sixty days before the date on which the intended closure is to become effective, a notice in the prescribed manner on the appropriate Government stating clearly the reasons for the intended closure of the establishment." },
      { no: "Section 33", title: "Conditions of Service to Remain Unchanged During Pendency of Proceedings — Protected Workman", keywords: ["protected workman", "service conditions", "disciplinary action", "pending proceedings", "trade union"], summary: "During the pendency of such proceedings in respect of an industrial dispute, the employer shall not alter to the prejudice of the workmen concerned in such dispute, the conditions of service applicable to them immediately before the commencement of such proceedings; nor shall he, for any misconduct connected with the dispute, discharge or punish, whether by dismissal or otherwise, any workman concerned in such dispute." },
    ],
  },
  {
    id: 702,
    category: "labor",
    title: "Minimum Wages Act 1948",
    subtitle: "Fixes minimum rates of wages for certain employments",
    sections: [
      { no: "Section 3", title: "Fixing of Minimum Rates of Wages", keywords: ["minimum wages", "fixing", "scheduled employment", "government", "rate"], summary: "The appropriate Government shall, in the manner hereinafter provided, fix the minimum rates of wages payable to employees employed in a scheduled employment specified in Part I or Part II of the Schedule and review and, if necessary, revise such minimum rates at such intervals as it may think fit, such intervals not exceeding five years." },
      { no: "Section 12", title: "Payment of Minimum Wages", keywords: ["payment", "minimum wages", "employee", "employer", "obligation", "entitled"], summary: "Where in respect of any scheduled employment a notification under section 5 is in force, the employer shall pay to every employee engaged in a scheduled employment under him wages at a rate not less than the minimum rate of wages fixed by such notification for that class of employees in that employment." },
      { no: "Section 22", title: "Penalties for Offences Under the Act", keywords: ["penalty", "imprisonment", "fine", "minimum wages", "offence", "violation"], summary: "Any employer who pays to any employee less than the minimum rates of wages fixed for that employee's class of work, or who contravenes any rule or order made under section 13 of this Act shall be punishable with imprisonment for a term which may extend to six months, or with fine which may extend to five hundred rupees, or with both." },
    ],
  },
  {
    id: 703,
    category: "labor",
    title: "Employees' Provident Funds and Miscellaneous Provisions Act 1952",
    subtitle: "Provides for provident fund and pension for employees",
    sections: [
      { no: "Section 6", title: "Contributions and Matters Which May Be Provided for in Schemes", keywords: ["EPF", "contribution", "12 percent", "employer", "employee", "provident fund"], summary: "The contribution which shall be paid by the employer to the Fund shall be twelve per cent of the basic wages, dearness allowance and retaining allowance (if any) for the time being payable to each of the employees, and the employees' contribution shall be equal to the contribution payable by the employer in respect of him." },
      { no: "Section 7A", title: "Determination of Moneys Due from Employers", keywords: ["PF", "due", "employer", "determination", "authority", "EPFO"], summary: "The Central Provident Fund Commissioner, any Additional Central Provident Fund Commissioner, any Deputy Provident Fund Commissioner or any Regional Provident Fund Commissioner or any Assistant Provident Fund Commissioner may, by order, determine the amount due from any employer under any provision of this Act." },
      { no: "Section 14", title: "Penalties — For Non-Payment of Contributions", keywords: ["penalty", "PF", "contribution", "imprisonment", "employer", "default"], summary: "Whoever, for the purpose of avoiding any payment to be made by himself under this Act, wilfully makes or causes to be made any false statement or false representation, shall be punishable with imprisonment for a term which may extend to one year or with fine of five thousand rupees or with both. In cases of default in payment of contribution, interest at rate of 12% per annum and penalty up to 100% of amount due may be imposed." },
    ],
  },
  {
    id: 704,
    category: "labor",
    title: "Maternity Benefit Act 1961",
    subtitle: "Protects employment of women during maternity",
    sections: [
      { no: "Section 5", title: "Right to Payment of Maternity Benefit", keywords: ["maternity benefit", "26 weeks", "mother", "leave", "pregnancy", "paid leave"], summary: "Subject to the provisions of this Act, every woman shall be entitled to, and her employer shall be liable for, the payment of maternity benefit at the rate of the average daily wage for the period of her actual absence, that is to say, the period immediately preceding the day of her delivery, the actual day of her delivery and any period immediately following that day. The period of maternity benefit is 26 weeks for the first two children." },
      { no: "Section 5A", title: "Continuance of Payment of Maternity Benefit in Certain Cases", keywords: ["maternity", "miscarriage", "medical termination", "6 weeks", "right"], summary: "In the case of miscarriage or medical termination of pregnancy, a woman shall, on production of such proof as may be prescribed, be entitled to maternity benefit for a period of six weeks immediately following the day of her miscarriage or medical termination of pregnancy." },
      { no: "Section 11", title: "Nursing Breaks", keywords: ["nursing", "breastfeeding", "intervals", "15 months", "work from home", "creche"], summary: "Every woman delivered of a child who returns to duty after such delivery shall, in addition to the interval for rest allowed to her, be allowed in the course of her daily work two breaks of the prescribed duration for nursing the child until the child attains the age of fifteen months. Employer to provide creche facility if more than 50 employees." },
      { no: "Section 12", title: "Dismissal During Absence — Prohibition", keywords: ["dismissal", "pregnancy", "maternity", "protection", "prohibition", "absent"], summary: "When a woman absents herself from work in accordance with the provisions of this Act, it shall be unlawful for her employer to discharge or dismiss her during or on account of such absence or to give notice of discharge or dismissal on such a day that the notice will expire during such absence, or to vary to her disadvantage any of the conditions of her service." },
    ],
  },
  {
    id: 705,
    category: "labor",
    title: "Factories Act 1948",
    subtitle: "Regulates health, safety and welfare in factories",
    sections: [
      { no: "Section 11", title: "Cleanliness", keywords: ["cleanliness", "factory", "health", "workplace", "sanitation", "worker"], summary: "Every factory shall be kept clean and free from effluvia arising from any drain, privy or other nuisance, and in particular accumulation of dirt and refuse shall be removed daily; the floor of every workroom shall be cleaned at least once in every week by washing, using disinfectant where necessary, or by some other effective method; effective means shall be provided and maintained for draining the floors of workrooms." },
      { no: "Section 22", title: "Work on or Near Machinery in Motion", keywords: ["machinery", "motion", "safety", "gear", "guard", "worker", "danger"], summary: "In any factory, it shall not be permissible to carry out examinations or to carry out lubrication or other adjusting operation while the machinery is in motion if such examination or operation exposes the examining or operating person to risk of injury from any moving part of that or any adjacent machinery." },
      { no: "Section 51", title: "Weekly Hours — Maximum 48 Hours", keywords: ["working hours", "48 hours", "weekly", "factory worker", "maximum hours"], summary: "No adult worker shall be required or allowed to work in a factory for more than forty-eight hours in any week." },
      { no: "Section 54", title: "Daily Hours — Maximum 9 Hours", keywords: ["daily hours", "9 hours", "factory", "worker", "maximum", "rest interval"], summary: "Subject to the provisions of section 51, no adult worker shall be required or allowed to work in a factory for more than nine hours in any day." },
      { no: "Section 59", title: "Extra Wages for Overtime", keywords: ["overtime", "extra wages", "double rate", "overtime payment", "factory", "worker"], summary: "Where a worker works in a factory for more than nine hours in any day or for more than forty-eight hours in any week, he shall, in respect of overtime work, be entitled to wages at the rate of twice his ordinary rate of wages." },
      { no: "Section 79", title: "Annual Leave with Wages", keywords: ["annual leave", "earned leave", "EL", "240 days", "factory worker", "wages"], summary: "Every worker who has worked for a period of 240 days or more in a factory during a calendar year shall be allowed during the subsequent calendar year, leave with wages for a number of days calculated at the rate of one day for every twenty days of work performed by him during the previous calendar year if he is an adult." },
    ],
  },
  {
    id: 706,
    category: "labor",
    title: "Code on Wages 2019",
    subtitle: "Consolidates 4 wage-related labour laws",
    sections: [
      { no: "Section 2(y)", title: "Definition of Wages Under Code on Wages", keywords: ["wages", "definition", "basic pay", "allowances", "DA", "code on wages"], summary: "'Wages' means all remuneration whether by way of salaries, allowances or otherwise, expressed in terms of money or capable of being so expressed which would, if the terms of employment, express or implied, were fulfilled, be payable to a person employed in respect of his employment or of work done in such employment, and includes basic pay; dearness allowance; retaining allowance, if any." },
      { no: "Section 43", title: "Floor Wage", keywords: ["floor wage", "minimum", "national wage floor", "all workers", "central government"], summary: "The Central Government may, having regard to the minimum living standards of a worker, fix a floor wage at the national level. The appropriate Government shall fix the minimum wages for the scheduled employments specified in the Schedule in respect of employees and such minimum wages shall not be less than the floor wage so fixed by the Central Government." },
      { no: "Section 56", title: "Determination of Bonus Payable", keywords: ["bonus", "8.33 percent", "20 percent", "annual bonus", "employee", "payment"], summary: "Where in an accounting year an employer is obliged to pay bonus to employees, the minimum bonus which an employer is required to pay to an employee in respect of the accounting year referred to in section 54 shall be eight and one-third per cent of the wages earned by the employee during the accounting year or one hundred rupees, whichever is higher, whether or not the employer has any allocable surplus in the accounting year. Maximum bonus shall not exceed twenty per cent of wages." },
    ],
  },
  {
    id: 707,
    category: "labor",
    title: "Sexual Harassment of Women at Workplace Act 2013 (POSH)",
    subtitle: "Prevents sexual harassment of women at the workplace",
    sections: [
      { no: "Section 2(n)", title: "Definition of Sexual Harassment", keywords: ["sexual harassment", "workplace", "definition", "unwelcome", "physical contact", "POSH"], summary: "'Sexual harassment' includes any one or more of the following unwelcome acts or behaviour (whether directly or by implication): physical contact and advances; a demand or request for sexual favours; making sexually coloured remarks; showing pornography; any other unwelcome physical, verbal or non-verbal conduct of sexual nature." },
      { no: "Section 4", title: "Constitution of Internal Complaints Committee (ICC)", keywords: ["ICC", "internal complaints committee", "POSH", "employer", "constitution", "10 employees"], summary: "Every employer of a workplace shall, by an order in writing, constitute a Committee to be known as the 'Internal Complaints Committee'. The Internal Complaints Committee shall consist of a Presiding Officer who shall be a woman employed at a senior level at the workplace from amongst the employees; not less than two Members from amongst employees preferably committed to the cause of women or who have had experience in social work or have legal knowledge; one member from amongst non-governmental organisations or associations committed to the cause of women." },
      { no: "Section 11", title: "Conciliation", keywords: ["conciliation", "settlement", "complaint", "sexual harassment", "POSH", "resolution"], summary: "Before initiating an inquiry, the Internal Committee may, at the request of the aggrieved woman, take steps to settle the matter between her and the respondent through conciliation." },
      { no: "Section 13", title: "Inquiry Report — Action by Employer", keywords: ["inquiry", "report", "employer", "action", "POSH", "termination", "warning"], summary: "On the recommendation of the Internal Committee where the allegation against the respondent has been proved, it shall be the duty of the employer to take action for sexual harassment as a misconduct in accordance with the provisions of the service rules applicable to the respondent or where no such service rules have been made, in such manner as may be prescribed — termination of service being the most severe consequence." },
    ],
  },
];
