import { Law } from "../types";

export const propertyLaws: Law[] = [
  {
    id: 801,
    category: "property",
    title: "Transfer of Property Act 1882",
    subtitle: "Governs transfer of property between persons",
    sections: [
      { no: "Section 5", title: "Transfer of Property — Definition", keywords: ["transfer", "property", "definition", "conveyance", "living persons", "act"], summary: "In the following sections 'transfer of property' means an act by which a living person conveys property, in present or in future, to one or more other living persons, or to himself, or to himself and one or more other living persons; and 'to transfer property' is to perform such act." },
      { no: "Section 6", title: "What May be Transferred", keywords: ["transfer", "property", "what may", "chance", "right", "mere right to sue"], summary: "Property of any kind may be transferred, except as otherwise provided by this Act or by any other law for the time being in force. The chance of a relation obtaining a legacy on the death of a kinsman; a mere right of re-entry for breach of a condition subsequent; an easement apart from the dominant heritage; an interest in property restricted in its enjoyment to the owner personally; a right to future maintenance; a mere right to sue cannot be transferred." },
      { no: "Section 17", title: "Direction for Accumulation — Rule Against Perpetuity", keywords: ["accumulation", "trust", "rule against perpetuity", "property", "18 years", "time limit"], summary: "No direction for the accumulation of income of property shall be valid unless it is for one of the following purposes: payment of the debts of the transferor or any other person taking any interest under the disposition; provision for payment of portions for children or remoter issue of the transferor; the preservation or maintenance of any property given under that disposition; if the period of accumulation does not exceed eighteen years." },
      { no: "Section 54", title: "Sale — Definition", keywords: ["sale", "definition", "ownership", "price", "money", "transfer"], summary: "'Sale' is a transfer of ownership in exchange for a price paid or promised or part-paid and part-promised. Sale of tangible immoveable property of the value of one hundred rupees and upwards, or sale of reversion or other intangible thing can only be made by a registered instrument. Tangible immoveable property of a value less than one hundred rupees may be transferred either by a registered instrument or by delivery of the property." },
      { no: "Section 58", title: "Mortgage — Definition and Its Different Forms", keywords: ["mortgage", "immoveable property", "loan", "security", "simple mortgage", "usufructuary", "equitable"], summary: "A mortgage is the transfer of an interest in specific immoveable property for the purpose of securing the payment of money advanced or to be advanced by way of loan, an existing or future debt, or the performance of an engagement which may give rise to a pecuniary liability. Forms of mortgage: Simple Mortgage; Mortgage by Conditional Sale; Usufructuary Mortgage; English Mortgage; Mortgage by Deposit of Title Deeds (Equitable Mortgage); Anomalous Mortgage." },
      { no: "Section 105", title: "Lease — Definition", keywords: ["lease", "definition", "immoveable property", "rent", "lessor", "lessee", "term"], summary: "A lease of immoveable property is a transfer of a right to enjoy such property, made for a certain time, express or implied, or in perpetuity, in consideration of a price paid or promised, or of money, a share of crops, service or any other thing of value, to be rendered periodically or on specified occasions to the transferor by the transferee, who accepts the transfer on such terms." },
      { no: "Section 108", title: "Rights and Liabilities of Lessor and Lessee", keywords: ["lessor", "lessee", "rights", "liabilities", "repairs", "rent", "lease agreement"], summary: "In the absence of a contract or local law or usage to the contrary, the lessor and lessee shall respectively possess the rights and be subject to the liabilities mentioned in the following rules: the lessor is bound to disclose material defects in property; the lessee shall give notice of encroachments before adverse possession; the lessee is bound to pay the premium or rent; the lessee is bound to maintain the property as a prudent owner." },
      { no: "Section 118", title: "Exchange — Definition", keywords: ["exchange", "definition", "property", "mutual transfer", "ownership"], summary: "When two persons mutually transfer the ownership of one thing for the ownership of another, neither thing or both things being money only, the transaction is called an 'exchange'. A transfer of property in completion of an exchange can be made only in manner provided for the transfer of such property by sale." },
      { no: "Section 122", title: "Gift — Definition", keywords: ["gift", "definition", "voluntary", "gratuitous", "transfer", "donor", "donee"], summary: "'Gift' is the transfer of certain existing moveable or immoveable property made voluntarily and without consideration, by one person, called the donor, to another, called the donee, and accepted by or on behalf of the donee." },
      { no: "Section 123", title: "Transfer How Effected — Registration of Gift Deed", keywords: ["gift", "registration", "gift deed", "immoveable property", "attestation", "attested"], summary: "For the purpose of making a gift of immoveable property, the transfer must be effected by a registered instrument signed by or on behalf of the donor, and attested by at least two witnesses. For the purpose of making a gift of moveable property, the transfer may be effected either by a registered instrument signed as aforesaid or by delivery." },
      { no: "Section 130", title: "Transfer of Actionable Claim", keywords: ["actionable claim", "debt", "transfer", "assignment", "notice", "creditor"], summary: "The transfer of an actionable claim whether with or without consideration shall be effected only by the execution of an instrument in writing signed by the transferor or his duly authorised agent, shall be complete and effectual upon the execution of such instrument, and thereupon all the rights and remedies of the transferor, whether by way of damages or otherwise, shall vest in the transferee." },
    ],
  },
  {
    id: 802,
    category: "property",
    title: "Registration Act 1908",
    subtitle: "Governs registration of documents in India",
    sections: [
      { no: "Section 17", title: "Documents of Which Registration is Compulsory", keywords: ["compulsory registration", "sale deed", "gift deed", "lease", "immoveable property", "100 years"], summary: "The following documents shall be registered: instruments of gift of immoveable property; other non-testamentary instruments which purport or operate to create, declare, assign, limit or extinguish, whether in present or in future, any right, title or interest, whether vested or contingent, of the value of one hundred rupees and upwards, to or in immoveable property; non-testamentary instruments which acknowledge the receipt or payment of any consideration on account of the creation, declaration, assignment, limitation or extinction of any such right, title or interest; leases of immoveable property from year to year, or for any term exceeding one year, or reserving a yearly rent." },
      { no: "Section 18", title: "Documents of Which Registration is Optional", keywords: ["optional registration", "document", "instruments", "moveable property", "will"], summary: "Any of the following documents may be registered under this Act, namely: instruments (other than instruments of gift and wills) which purport or operate to create, declare, assign, limit or extinguish, whether in present or in future, any right, title or interest in immoveable property where the value of such right, title or interest is less than one hundred rupees; instruments transferring or assigning any decree or order of a Court or any award when such decree, order or award purports or operates to create, declare, assign, limit or extinguish, whether in present or in future, any right, title or interest, whether vested or contingent, of the value of one hundred rupees and upwards, to or in immoveable property." },
      { no: "Section 49", title: "Effect of Non-Registration of Documents Required to Be Registered", keywords: ["non-registration", "effect", "unregistered", "document", "invalid", "evidence"], summary: "No document required by section 17 or by any provision of the Transfer of Property Act, 1882, to be registered shall affect any immoveable property comprised therein, or confer any power to adopt, or be received as evidence of any transaction affecting such property or conferring such power, unless it has been registered." },
    ],
  },
  {
    id: 803,
    category: "property",
    title: "Real Estate (Regulation and Development) Act 2016 (RERA)",
    subtitle: "Regulates the real estate sector in India",
    sections: [
      { no: "Section 3", title: "Prior Registration of Real Estate Project", keywords: ["RERA", "registration", "project", "developer", "builder", "500 sq m", "8 apartments"], summary: "No promoter shall advertise, market, book, sell or offer for sale, or invite persons to purchase in any manner any plot, apartment or building, as the case may be, in any real estate project or part of it, in any planning area, without registering the real estate project with the Real Estate Regulatory Authority established under this Act. Projects above 500 sq m or 8 apartments must be registered." },
      { no: "Section 4", title: "Application for Registration of Real Estate Project", keywords: ["application", "RERA", "registration", "builder", "documents", "promoter"], summary: "Every promoter shall make an application to the Authority for registration of the real estate project in such form, manner, within such time and accompanied by such fee as may be prescribed. The application shall contain the details of proposed facilities and amenities, sanctioned plan, layout plan and specifications of the proposed project, proposed number of apartments, proposed dates of completion, and such other information and documents as may be prescribed." },
      { no: "Section 11", title: "Functions and Duties of Promoter — Disclosures", keywords: ["promoter", "builder", "disclosures", "obligations", "website", "RERA", "transparency"], summary: "The promoter shall make available the information regarding the real estate project on the website of the Authority, in such form and manner as may be prescribed, including the sanctioned plan, layout plan along with specifications, approved by the competent authority; the plan of development works to be executed in the proposed project; the location of the project, with clear demarcation of land dedicated for the project along with its boundaries including the latitude and longitude of the end points of the project." },
      { no: "Section 13", title: "No Deposit or Advance to be Taken Without Agreement for Sale — 10 Percent Cap", keywords: ["advance", "deposit", "10 percent", "agreement for sale", "buyer", "RERA", "protect"], summary: "A promoter shall not accept a sum more than ten per cent of the cost of the apartment, plot, or building as the case may be, as an advance payment or an application fee, from a person without first entering into a written agreement for sale with such person and registering the said agreement for sale, under any law for the time being in force." },
      { no: "Section 18", title: "Return of Amount and Compensation on Non-Completion", keywords: ["refund", "compensation", "delay", "builder", "default", "RERA", "buyer"], summary: "If the promoter fails to complete or is unable to give possession of an apartment, plot or building in accordance with the terms of the agreement for sale or, as the case may be, duly completed by the date specified therein, the promoter shall be liable on demand to refund the amount received by him in respect thereof with interest at such rate as may be prescribed in this behalf including compensation in the manner as provided under this Act." },
      { no: "Section 19", title: "Rights and Duties of Allottee (Buyer)", keywords: ["allottee", "buyer", "rights", "duties", "information", "RERA", "apartment"], summary: "Every allottee, who has entered into an agreement for sale to take an apartment, plot or building as the case may be under section 13, shall be entitled to obtain the information relating to sanctioned plans, layout plans along with the specifications, approved by the competent authority and such other information as provided in this Act or the rules and regulations made thereunder. The allottee shall be required to make payments in the specified time and in the manner as specified under the terms and conditions of the agreement for sale and shall be liable to pay interest, at such rate as may be prescribed, for any delay in payment towards any amount or charges to be paid." },
      { no: "Section 31", title: "Filing of Complaints With Authority or Adjudicating Officer", keywords: ["complaint", "RERA", "buyer", "allottee", "authority", "redressal"], summary: "Any aggrieved person may file a complaint with the Authority or the adjudicating officer, as the case may be, for any violation or contravention of the provisions of this Act or the rules and regulations made thereunder against any promoter allottee or real estate agent." },
      { no: "Section 35", title: "Powers of Authority — Investigation", keywords: ["RERA", "authority", "power", "investigation", "inquiry", "builder"], summary: "The Authority shall have powers to call for information from, conduct investigations and inspections of the affairs of any real estate project, promoter or allottee. The Authority shall investigate any matter relating to the violation of any provisions of this Act, or the rules and regulations made thereunder, by a promoter, allottee or real estate agent." },
      { no: "Section 61", title: "Penalty for Non-Registration of Real Estate Project", keywords: ["penalty", "non-registration", "RERA", "builder", "10 percent", "project cost"], summary: "If any promoter contravenes the provisions of section 3, he shall be liable to a penalty which may extend up to ten per cent of the estimated cost of the real estate project as determined by the Authority. If any promoter does not comply with the orders, decisions or directions issued under section 3 he shall be punishable with imprisonment for a term which may extend up to three years or with fine which may extend up to a further ten per cent of the estimated cost of the real estate project, or with both." },
    ],
  },
  {
    id: 804,
    category: "property",
    title: "Indian Easements Act 1882",
    subtitle: "Governs easements and licences in property law",
    sections: [
      { no: "Section 4", title: "Definition of Easement and Its Origin", keywords: ["easement", "right", "land", "enjoy", "owner", "pass", "drain"], summary: "An easement is a right which the owner or occupier of certain land possesses, as such, for the beneficial enjoyment of that land, to do and continue to do something, or to prevent and continue to prevent something being done, in or upon, or in respect of, certain other land not his own. The land for the beneficial enjoyment of which the right exists is called the dominant heritage; the land on which the liability is imposed is called the servient heritage." },
      { no: "Section 15", title: "Easements by Prescription — 20 Years", keywords: ["prescription", "20 years", "easement", "right", "long use", "adverse"], summary: "Where the access and use of light or air to and for any building have been peaceably enjoyed therewith, as an easement, without interruption, and for twenty years, and where any other easement has been peaceably and openly enjoyed by the person claiming it, as an easement, and as of right, without interruption, and for twenty years, the right to such access and use of light or air, or to such other easement, shall be absolute." },
    ],
  },
];
